// Prototype local. The complete edition should be generated by indexing both 1930 volumes.
window.MEDITATIONS = {
  "09-15": {
    title: "L’Amour mutuel",
    quote: "« Je vous donne un commandement nouveau, que vous vous aimiez les uns les autres. »",
    body: [
      "Saint Thomas présente la charité fraternelle comme une véritable amitié fondée sur un bien commun : Dieu lui-même.",
      "Le Christ nous aime gratuitement, efficacement et selon les lois de l’amitié. L’amour chrétien ne se réduit donc ni au sentiment ni à l’utilité : il veut réellement le bien de l’autre et l’ordonne à Dieu."
    ],
    practice: "Accomplir aujourd’hui un acte de charité envers quelqu’un sans attendre de retour.",
    source: "Tome II — Sur saint Jean, chapitre XIII"
  },
  "09-16": {
    title: "Le nouveau commandement d’amour",
    quote: "« Je vous donne un commandement nouveau, que vous vous aimiez les uns les autres. »",
    body: [
      "Le précepte d’aimer le prochain existait déjà dans l’Ancienne Loi. Sa nouveauté chrétienne tient au renouvellement intérieur produit par la charité.",
      "Cette nouveauté vient aussi de l’Esprit d’adoption : l’homme n’agit plus seulement sous la crainte servile, mais comme fils, poussé intérieurement par l’amour. Enfin, la charité est propre à la Nouvelle Alliance en tant que loi écrite dans le cœur."
    ],
    practice: "Choisir un bien à faire aujourd’hui non parce qu’il est imposé, mais librement, par amour du bien et du prochain.",
    source: "Tome II — Sur saint Jean, chapitre XIII"
  },
  "09-17": {
    title: "Comment est possible l’amour parfait du prochain",
    quote: "La perfection de la charité se mesure à la manière dont le prochain est aimé en Dieu.",
    body: [
      "La charité parfaite ne s’arrête pas aux affinités naturelles. Elle fait aimer le prochain pour Dieu et selon Dieu.",
      "Plus l’amour est purifié de la recherche de soi, plus il devient universel, ordonné et véritablement surnaturel."
    ],
    practice: "Prier aujourd’hui pour une personne que l’on aime peu spontanément, en demandant son vrai bien.",
    source: "Tome II — entrée du 17 septembre"
  }
};
